"""
Interactive CLI for Core Coder V1
================================================

Command-line interface with:
- Interactive conversation mode
- Safety controls
- Conversation memory

Generated by Agent Forge™
"""

import sys
import os
from pathlib import Path
try:
    from colorama import init, Fore, Style, Back, just_fix_windows_console
    # Use modern Windows console fix if available (supports TrueColor)
    just_fix_windows_console()
except (ImportError, AttributeError):
    from colorama import init, Fore, Style, Back
    # Fallback for older colorama or non-Windows
    init()

# Add current directory to path
sys.path.insert(0, str(Path(__file__).parent))

from coding_agent import create_agent, AGENT_CONFIG
from dotenv import load_dotenv

# Load environment variables
load_dotenv()


class Colors:
    """Handle color schemes for the CLI."""
    
    SCHEMES = {
        "custom": {
            "agent": "\033[38;2;216;216;218m",
            "user": "\033[38;2;18;147;253m",
            "system": "\033[38;2;117;243;32m",
            "error": "\033[38;2;243;43;53m",
            "success": "\033[38;2;46;234;93m",
            "warning": "\033[38;2;241;219;75m",
            "dim": "\033[2m",
            "reset": "\033[0m"
        },
        "dracula": {
            "agent": Fore.MAGENTA,
            "user": Fore.CYAN,
            "system": Fore.WHITE,
            "error": Fore.RED,
            "success": Fore.GREEN,
            "warning": Fore.YELLOW,
            "dim": Style.DIM,
            "reset": Style.RESET_ALL
        },
        "matrix": {
            "agent": Fore.GREEN,
            "user": Fore.LIGHTGREEN_EX,
            "system": Fore.LIGHTBLACK_EX,
            "error": Fore.RED,
            "success": Fore.LIGHTGREEN_EX,
            "warning": Fore.YELLOW,
            "dim": Style.DIM,
            "reset": Style.RESET_ALL
        },
        "monokai": {
            "agent": Fore.YELLOW,
            "user": Fore.LIGHTBLUE_EX,
            "system": Fore.WHITE,
            "error": Fore.RED,
            "success": Fore.GREEN,
            "warning": Fore.MAGENTA,
            "dim": Style.DIM,
            "reset": Style.RESET_ALL
        },
        "cyberpunk": {
            "agent": Fore.CYAN,
            "user": Fore.MAGENTA,
            "system": Fore.YELLOW,
            "error": Fore.RED,
            "success": Fore.GREEN,
            "warning": Fore.LIGHTRED_EX,
            "dim": Style.DIM,
            "reset": Style.RESET_ALL
        },
        "default": {
            "agent": Fore.BLUE,
            "user": Fore.GREEN,
            "system": Fore.WHITE,
            "error": Fore.RED,
            "success": Fore.GREEN,
            "warning": Fore.YELLOW,
            "dim": Style.DIM,
            "reset": Style.RESET_ALL
        }
    }
    
    def __init__(self, scheme_name="default"):
        self.scheme = self.SCHEMES.get(scheme_name, self.SCHEMES["default"])
    
    def get(self, key):
        return self.scheme.get(key, Fore.WHITE)


class AgentCLI:
    """Interactive CLI for Core Coder V1."""
    
    def __init__(self, project_dir: str = ".", enable_memory: bool = True, session_id: str = None):
        """Initialize the CLI."""
        self.project_dir = Path(project_dir).resolve()
        self.enable_memory = enable_memory
        self.session_id = session_id or f"session_{AGENT_CONFIG['name']}"
        
        # Setup colors
        scheme_name = AGENT_CONFIG.get("color_scheme", "default")
        # Debug print to verify scheme selection (can be removed later)
        # print(f"DEBUG: Active Color Scheme: {scheme_name}")
        self.colors = Colors(scheme_name)
        self.c_agent = self.colors.get("agent")
        self.c_user = self.colors.get("user")
        self.c_sys = self.colors.get("system")
        self.c_err = self.colors.get("error")
        self.c_reset = self.colors.get("reset")
        
        # Verify API key
        if AGENT_CONFIG.get("provider") == "groq" and not os.getenv('GROQ_API_KEY'):
            print(f"{self.c_err}[ERROR] Error: GROQ_API_KEY not found in environment{self.c_reset}")
            print("   Please create a .env file with your API key:")
            print("   GROQ_API_KEY=your_key_here")
            sys.exit(1)
        
        # Create agent
        print(f"{self.c_sys}Initializing {AGENT_CONFIG['display_name']}...{self.c_reset}")
        self.agent = create_agent(
            project_directory=str(self.project_dir),
            enable_memory=enable_memory,
            session_id=self.session_id
        )
        
        print(f"{self.colors.get('success')}Agent ready!{self.c_reset}\n")
    
    def run(self):
        """Run the interactive CLI."""
        print(f"{self.c_sys}{'='*70}")
        print(f"  {AGENT_CONFIG['display_name']} - Interactive Mode")
        print(f"{'='*70}{self.c_reset}")
        print()
        print(f"{self.c_sys}Commands:")
        print("  - Type your message and press Enter")
        print("  - Type 'exit' or 'quit' to exit")
        print("  - Type 'clear' to clear screen")
        print(f"  - Type 'help' for help{self.c_reset}")
        print()
        print(f"{self.c_sys}{'='*70}{self.c_reset}\n")
        
        while True:
            try:
                # Get user input
                user_input = input(f"\n{self.c_user}You: {self.c_reset}").strip()
                
                if not user_input:
                    continue
                
                # Handle commands
                if user_input.lower() in ['exit', 'quit', 'q']:
                    print(f"\n{self.c_sys}Goodbye!{self.c_reset}\n")
                    break
                
                if user_input.lower() == 'clear':
                    os.system('cls' if os.name == 'nt' else 'clear')
                    continue
                
                if user_input.lower() == 'help':
                    self.show_help()
                    continue
                
                # Send to agent
                print(f"\n{self.c_agent}Agent: ", end="", flush=True)
                
                response = self.agent.chat(
                    user_input,
                    session_id=self.session_id
                )
                
                # Ensure agent color is applied to the response
                print(f"{self.c_agent}{response}{self.c_reset}")
                
            except KeyboardInterrupt:
                print(f"\n\n{self.c_sys}Goodbye!{self.c_reset}\n")
                break
            except Exception as e:
                print(f"\n{self.c_err}Error: {e}{self.c_reset}\n")
    
    def show_help(self):
        """Show help information."""
        print(f"\n{self.c_sys}" + "="*70)
        print(f"  {AGENT_CONFIG['display_name']} - Help")
        print("="*70)
        print()
        print("Available Commands:")
        print("  exit, quit, q  - Exit the CLI")
        print("  clear          - Clear the screen")
        print("  help           - Show this help message")
        print()
        print("Features:")
        print(f"  - Model: {AGENT_CONFIG['model']}")
        print(f"  - Memory: {'Enabled' if self.enable_memory else 'Disabled'}")
        print(f"  - RAG: {'Enabled' if AGENT_CONFIG['rag_enabled'] else 'Disabled'}")
        print(f"  - Tools: {len(self.agent.list_tools())} available")
        print()
        print(f"="*70 + f"{self.c_reset}")


def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description=f"{AGENT_CONFIG['display_name']} - CLI Interface",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python cli.py                          # Start interactive mode
  python cli.py --no-memory              # Start without memory
  python cli.py /path/to/project         # Specify project directory
  python cli.py --session my_session     # Custom session ID
        """
    )
    
    parser.add_argument(
        "project_dir",
        nargs="?",
        default=".",
        help="Project directory (default: current directory)"
    )
    
    parser.add_argument(
        "--no-memory",
        action="store_true",
        help="Disable memory and RAG"
    )
    
    parser.add_argument(
        "--session",
        type=str,
        default=None,
        help="Custom session ID"
    )
    
    args = parser.parse_args()
    
    # Validate project directory
    project_path = Path(args.project_dir).resolve()
    if not project_path.exists():
        print(f"❌ Error: Directory does not exist: {args.project_dir}")
        sys.exit(1)
    
    if not project_path.is_dir():
        print(f"❌ Error: Not a directory: {args.project_dir}")
        sys.exit(1)
    
    # Start CLI
    enable_memory = not args.no_memory
    cli = AgentCLI(
        str(project_path),
        enable_memory=enable_memory,
        session_id=args.session
    )
    cli.run()


if __name__ == "__main__":
    main()
